language: python
python:
  - "3.5"
# command to run tests
before_install:
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r requirements.txt
install:
    - pip install codecov
script: 
  - python -m PyEMD.tests.test_all
  - coverage run PyEMD/tests/test_all.py
after_success:
  - codecov
